# -----------------------------
# Server
# -----------------------------
server.port=7070

# -----------------------------
# PostgreSQL
# -----------------------------
db.url=jdbc:postgresql://localhost:5432/rate_limiter
db.username=postgres
db.password=root

# -----------------------------
# Redis
# -----------------------------
redis.url=redis://localhost:6379

# -----------------------------
# Logging
# -----------------------------
logging.level=INFO